### ISSUE TITLE
searchSRA maps extremely small sequences

### ISSUE THREAD

**Issue by xvazquezc** [linsalrob/SearchSRA#2]
Hi @linsalrob,

I have been using the SearchSRA website in order to locate the presence of an operon in the environment. After downloading the results and filtering for candidate SRA records as detailed in [Search SRA Data](https://edwards.sdsu.edu/research/search-sra-data/), I realised that many of the good candidates (amongst others) are mapping really short reads, i.e. <10bp long. These are likely sequencing junk. I've seen them in not few Ion Torrent and Illumina records.

These very short reads probably reduce the utility of the mapping results as they are quite often rather random alignments and occupying a place for full length reads in the subset of SRA reads.

There is a way around this by using the `fastq-dump` option `-M`, which sets the minimum read size to be downloaded, and thus, avoiding using sequencing junk. Probably a value of 20, or at very least 10, would be a good implementation.

What do you think? I can make a pull request if you are ok with it.

Cheers,
Xabi

**Comment by linsalrob** [comment]
Hi Xabi

I have been hesitant to limit the data, as I don't really know what people are looking for. I agree that a minimum length would probably be a great option, and perhaps 35 or 50 bp would be more appropriate since with much shorter reads the error is huge. 

However, at the moment we have the philosophy of including everything and then letting users filter in the downstream (e.g. using [sam_len](https://github.com/linsalrob/sam#sam_len)

Rob
